name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.4.1
  permission_handler: ^11.3.1
  freezed_annotation: ^2.4.4
  flutter_bloc: ^8.1.6
  lottie: ^3.1.3
  animated_text_kit: ^4.2.1
  http: ^1.2.2
  wifi_iot: ^0.3.19+1
  open_settings: ^2.0.2
  quickalert: ^1.1.0
  connectivity_plus: ^6.1.0
  app_settings: ^5.1.1
  network_info_plus: ^6.1.1
  wifi_info_flutter: ^2.0.2
  blur: ^4.0.0
  flutter_animate: ^4.5.0
  


dev_dependencies:
  freezed: ^2.4.4
  build_runner: ^2.3.0
  json_serializable: ^6.5.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/catloading.json  
    - assets/images/
  fonts:
    - family: Lemon
      fonts:
       - asset: assets/fonts/Lemon-Regular.ttf

